jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 2020
   servlet:
      context-path: /microservicio
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: 
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: 
      username: postgres
      password: 
      hikari:
         poolName: pool
